### ISSUE TITLE
Global attribute standard_name_vocabulary 

### ISSUE THREAD

**Issue by MathewBiddle** [MathewBiddle/ATN-archive#5]
The global attribute `standard_name_vocabulary` should be `CF Standard Name Table v77` as that's the most recent published version at https://cfconventions.org/standard-names.html and what we should be using to populate the `standard_name` attributes.

https://github.com/MathewBiddle/ATN-archive/blob/b738cbcf3836f50a3b518790662e376b7e3ad0d1/data/deployment_km_greyseal_v1.ncdump#L227

**Comment by iamchrisser** [comment]
We're using CF-v77, it's just that attribute that's out of sync. I'll change it in the example file and someone else will fix the it in the pipeline that generates our netCDF files.

**Comment by MathewBiddle** [comment]
From @iamchrisser 
* This attribute has been updated to reference CF v77. We were already using 77, but hadn't updated the netCDF creation script to write the correct value. Thanks for pinging us about this. 
See https://github.com/MathewBiddle/ATN-archive/blob/64bde94f37b4251696704ded97ecd80b766d7da4/templates/atn_trajectory_template_ncdump.txt#L263
