### ISSUE TITLE
ioos_category attribute

### ISSUE THREAD

**Issue by MathewBiddle** [MathewBiddle/ATN-archive#7]
The `ioos_category` attribute (found in multiple variables) is something ERDDAP automatically adds to a dataset. The vocabulary used there is rather useless and has no authoritative source. I suggest we remove it as it could cause confusion. You can see more discussion from Bob Simons [here](https://groups.google.com/g/erddap/c/TnwbgzpSS0w/m/ndisodLxAgAJ).

One example in the file:
https://github.com/MathewBiddle/ATN-archive/blob/b738cbcf3836f50a3b518790662e376b7e3ad0d1/data/deployment_km_greyseal_v1.ncdump#L34

**Comment by iamchrisser** [comment]
I've dropped this in the files added in the [most recent commit](https://github.com/MathewBiddle/ATN-archive/commit/d603e284a164f2f6a2f9856719cdd10ad631bf34).
